#!/usr/bin/env node
// Builds our own Lottie micro-animations.
//
//   npm run lottie:build
//
// Writes components/video/lottie/anims/<name>.json (one file each, so the
// player only loads what a video uses), manifest.json (category, loop,
// duration, description, for the Visual Director) and registry.ts (lazy
// loaders). Definitions live in scripts/lottie/animations.mjs.

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ANIMATIONS } from "./animations.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const outDir = path.join(root, "components/video/lottie");
const animDir = path.join(outDir, "anims");
mkdirSync(animDir, { recursive: true });
for (const f of readdirSync(animDir)) rmSync(path.join(animDir, f));

const manifest = {};
let total = 0;
for (const [name, def] of Object.entries(ANIMATIONS)) {
  const data = def.build();
  const json = JSON.stringify(data);
  writeFileSync(path.join(animDir, `${name}.json`), json);
  total += json.length;
  manifest[name] = { category: def.category, loop: def.loop, frames: data.op, description: def.description };
}
writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 1));

const names = Object.keys(manifest);
writeFileSync(
  path.join(outDir, "registry.ts"),
  `// Generated by scripts/lottie/build.mjs. Do not edit.\n` +
    `export const LOTTIE_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {\n` +
    names.map((n) => `  ${JSON.stringify(n)}: () => import("./anims/${n}.json"),`).join("\n") +
    `\n};\n`,
);
console.log(`lottie: ${names.length} animations, ${(total / 1024).toFixed(1)} KB total (${(total / names.length / 1024).toFixed(1)} KB avg)`);
