import { DURATION, END, at, kw } from "../fixtures/flowly";

// The Flowly voice's moments (frames) the four reference films are cut on.
export const T = {
  every: 0,
  data: at("data"),
  scattered: at("scattered"),
  tools: at("different tools"),
  sales: at("Sales"),
  payments: at("Payments"),
  reports: at("Reports"),
  flowly: at("Flowly"),
  brings: at("brings"),
  everything: at("everything"),
  into: at("into one"),
  live: at("live dashboard"),
  dashboard: at("dashboard."),
  when1: at("When a payment"),
  payment: at("payment arrives"),
  revenue: at("revenue updates"),
  updates: at("updates instantly"),
  instantly: at("instantly"),
  when2: at("When sales"),
  grow: at("grow"),
  entire: at("entire team"),
  team: at("team sees"),
  change: at("change in"),
  view: at("view."),
  no1: at("No more switching"),
  switching: at("switching"),
  between: at("between tools"),
  no2: at("No more waiting"),
  waiting: at("waiting"),
  reports2: at("for reports"),
  just: at("Just one"),
  live2: at("live dashboard with"),
  every2: at("every answer"),
  answer: at("answer"),
  need: at("need."),
  end: END,
  duration: DURATION,
};
export { kw };
